[package]
name = "feite"
version = "0.1.0"
edition = "2021"

[dependencies]
inkwell = { git = "https://github.com/TheDan64/inkwell", rev = "0cdaa34", features = ["llvm16-0"] }
llvm-sys = { version = "160.1.4", features = ["prefer-static"] }
